#!/bin/bash
# rustc calculates a unique metadata tag to mangle symbols which includes the
# actual path to the crate. This breaks our deterministic builds as we depend
# on a copy of rust-lightning via a path. We insert this shim between cargo and
# rustc and edit the metadata tag for rust-lightning.
# While we could just set RUSTFLAGS="-C metadata=42", this would break if we
# ever (indirectly) depend on multiple versions of the same crate.
args=("$@")
IS_LIGHTNING=false
SKIP_EMBED_BITCODE=false
MAY_NEED_COMPILER_BUILTINS=false
DEP_PATH=""
for ((i=0; i<"${#args[@]}"; ++i)); do
    case ${args[i]} in
        --crate-name)
			if [ "${args[i+1]}" = "lightning" -o "${args[i+1]}" = "lightning_types" -o "${args[i+1]}" = "lightning_background_processor" -o "${args[i+1]}" = "lightning_invoice" -o "${args[i+1]}" = "lightning_persister" -o "${args[i+1]}" = "lightning_rapid_gossip_sync" -o "${args[i+1]}" = "lightning_liquidity" -o "${args[i+1]}" = "lightning_transaction_sync" -o "${args[i+1]}" = "ldk" ]; then
				IS_LIGHTNING=true
			elif [ "${args[i+1]}" = "memchr" -o "${args[i+1]}" = "rustc_demangle" -o "${args[i+1]}" = "unwind" ]; then
				MAY_NEED_COMPILER_BUILTINS=true
			fi
			;;
		--crate-type)
			if [ "${args[i+1]}" = "proc-macro" ]; then
				# If we're building a proc-macro, rustc incorrectly passes our RUSTFLAGS containing
				# embed-bitcode=yes, which we don't want.
				SKIP_EMBED_BITCODE=true
			fi
			;;
		--extern)
			IFS="=" PAIR=(${args[i+1]})
			DEP_PATH="$(dirname ${PAIR[1]})"
			;;
    esac
done
for ((i=0; i<"${#args[@]}"; ++i)); do
    case ${args[i]} in
        metadata*)
			if [ "$IS_LIGHTNING" = "true" ]; then
				# Pick any random value for metadata, it doesn't matter
				args[i]="metadata=42"
			fi
			;;
		embed-bitcode=yes)
			if [ "$SKIP_EMBED_BITCODE" = "true" ]; then
				args[i]="embed-bitcode=no"
			fi
			;;
		lto)
			if [ "$SKIP_EMBED_BITCODE" = "true" ]; then
				args[i]="lto=no"
			fi
			;;
    esac
done

# For some reason, sometimes when building with build-std cargo forgets to give crates a path to
# their `compiler_builtin` dependencies. This obviously shouldn't happen but we fix it here.
EXTRA_ARGS=()
if [ "$MAY_NEED_COMPILER_BUILTINS" = "true" ]; then
	if [ -z "$DEP_PATH" ]; then
		echo "WARNING: Need at least one other dependency to know where to look, build may to fail if cargo is buggy" > /dev/stderr
	else
		COUNT=0
		CB_PATH="$(echo "$DEP_PATH"/libcompiler_builtins-*.rmeta)"
		while [ ! -f "$CB_PATH" ]; do
				# Wait until compiler_builtins finishes building...
				sleep 1
				COUNT="$(( $COUNT + 1 ))"
				if [ "$COUNT" -gt 120 ]; then
						echo "Took too long to get compiler_builtins built" > /dev/stderr
						exit 1
				fi
				CB_PATH="$(echo "$DEP_PATH"/libcompiler_builtins-*.rmeta)"
		done
		sleep 1
		EXTRA_ARGS=("--extern" compiler_builtins="$CB_PATH")
	fi
fi

$LDK_RUSTC_PATH "${args[@]}" "${EXTRA_ARGS[@]}"
